version: '3.8'

services:
    # Codeforces Application
  codeforces:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: codeforces
    depends_on:
      - mongodb
      - redis
      - opensearch
      - kafka
      - zookeeper
    ports:
      - "8080:3000"

  # Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka Message Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092         # Use if running docker also in docker-compose
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092      # Use if running docker outside docker-compose (locally)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Redis for Caching & Offsets
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    environment:
      REDIS_ARGS: --save 20 1 --appendonly yes
    ports:
      - "6379:6379"

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: true
    ports:
      - "9200:9200"

volumes:
  mongodb_data:
    driver: local