### Basics
quarkus.swagger-ui.always-include=false
quarkus.http.port=3000
quarkus.http.cors=true
quarkus.http.cors.origins=${HTTP_CORS_ORIGINS:http://localhost:3000}
quarkus.http.cors.methods=GET,POST,PUT,DELETE
quarkus.http.cors.headers=Content-Type,Authorization

### Codeforces Credentials
codeforces.apiKey=${CODEFORCES_API_KEY}
codeforces.apiSecret=${CODEFORCES_API_SECRET}
codeforces.randomString=${CODEFORCES_RANDOM_STRING:123456}

### Logging
quarkus.log.level=INFO
quarkus.log.category."org.dev".level=${APP_LOG_LEVEL:DEBUG}

### Backing services
kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING:mongodb://localhost:27017}
openSearch.host=${OPENSEARCH_HOST:localhost}
quarkus.redis.hosts=${REDIS_HOSTS:redis://localhost:6379}

### MongoDB
quarkus.mongodb.database=codeforces

### Kafka Topic - User Info
mp.messaging.outgoing.CFUserInfo.connector=smallrye-kafka
mp.messaging.outgoing.CFUserInfo.topic=codeforcesUserInfo
mp.messaging.outgoing.CFUserInfo.serializer=org.apache.kafka.common.serialization.StringSerializer

### Kafka Topic - Blog Entry
mp.messaging.outgoing.CFBlogEntry.connector=smallrye-kafka
mp.messaging.outgoing.CFBlogEntry.topic=codeforcesBlogEntry
mp.messaging.outgoing.CFBlogEntry.serializer=org.apache.kafka.common.serialization.StringSerializer

### MongoDB Consumer - User Info (Kafka -> MongoDB)
mp.messaging.incoming.UserInfoIn.connector=smallrye-kafka
mp.messaging.incoming.UserInfoIn.topic=codeforcesUserInfo
mp.messaging.incoming.UserInfoIn.group.id=mongodb-consumer
mp.messaging.incoming.UserInfoIn.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.UserInfoIn.partitions=1
mp.messaging.incoming.UserInfoIn.concurrency=1
mp.messaging.incoming.UserInfoIn.consumer-rebalance-listener.name=custom-rebalance-listener
mp.messaging.incoming.UserInfoIn.failure-strategy=dead-letter-queue
mp.messaging.incoming.UserInfoIn.dead-letter-queue.topic=codeforcesUserInfo-dlq

### MongoDB Consumer - Blog Entry (Kafka -> MongoDB)
mp.messaging.incoming.BlogEntryIn.connector=smallrye-kafka
mp.messaging.incoming.BlogEntryIn.topic=codeforcesBlogEntry
mp.messaging.incoming.BlogEntryIn.group.id=mongodb-consumer
mp.messaging.incoming.BlogEntryIn.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.BlogEntryIn.partitions=1
mp.messaging.incoming.BlogEntryIn.concurrency=1
mp.messaging.incoming.BlogEntryIn.consumer-rebalance-listener.name=custom-rebalance-listener
mp.messaging.incoming.BlogEntryIn.failure-strategy=dead-letter-queue
mp.messaging.incoming.BlogEntryIn.dead-letter-queue.topic=codeforcesBlogEntry-dlq

### OpenSearch
openSearch.port=${OPENSEARCH_PORT:9200}
