FROM amazoncorretto:21
WORKDIR /app
COPY --chown=185 build/quarkus-app/lib/ /deployments/lib/
COPY --chown=185 build/quarkus-app/*.jar /deployments/
COPY --chown=185 build/quarkus-app/app/ /deployments/app/
COPY --chown=185 build/quarkus-app/quarkus/ /deployments/quarkus/
EXPOSE 3000
WORKDIR /deployments
ENTRYPOINT ["java", "-jar", "quarkus-run.jar"]
